name: Philosophy Site CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Site
      run: |
        mkdir -p dist
        cp -r src/* dist/
        echo "Simple build complete!"