name: Philosophy Site CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # HTML Validation
    - name: Validate HTML
      run: |
        sudo apt-get install -y tidy
        for file in src/*.html; do
          tidy -q -errors "$file"
        done
    
    - name: Validate CSS
      run: |
        npm install -g stylelint
        stylelint "**/*.css"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    
    
    - name: Build Site
      run: |
        mkdir -p dist
        cp -r src/* dist/
        # If using Hugo: hugo --source ./src --destination ./dist

    # Archive build artifacts
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: philosophy-site
        path: dist/